### ISSUE TITLE
failed to upload due to GCS

### ISSUE THREAD

**Issue by plaNeDefiler** [daichirata/fluent-plugin-gcs#27]
``
2023-11-06 10:13:00 +0900 [debug]: #0 [gcs] Created new chunk chunk_id="609718e16bbf586a68ee2395e345b3f2" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1699233180, tag="reformed.test.https", variables=nil, seq=0>
2023-11-06 10:13:06 +0900 [warn]: #0 [gcs] got unrecoverable error in primary and no secondary error_class=ArgumentError error="wrong number of arguments (given 2, expected 1)"
  2023-11-06 10:13:06 +0900 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/google-cloud-storage-1.44.0/lib/google/cloud/storage/bucket.rb:1360:in `file'
  2023-11-06 10:13:06 +0900 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluent-plugin-gcs-0.4.0/lib/fluent/plugin/out_gcs.rb:170:in `generate_path'
  2023-11-06 10:13:06 +0900 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluent-plugin-gcs-0.4.0/lib/fluent/plugin/out_gcs.rb:119:in `write'
  2023-11-06 10:13:06 +0900 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluentd-1.16.2/lib/fluent/plugin/output.rb:1225:in `try_flush'
  2023-11-06 10:13:06 +0900 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluentd-1.16.2/lib/fluent/plugin/output.rb:1538:in `flush_thread_run'
  2023-11-06 10:13:06 +0900 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluentd-1.16.2/lib/fluent/plugin/output.rb:510:in `block (2 levels) in start'
  2023-11-06 10:13:06 +0900 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

using ruby 3.1.2

**Comment by plaNeDefiler** [comment]
solved with plugin 0.4.3
